/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.main;

import controller.Controller;
import form.doctor.FormAddDoctor;
import form.doctor.FormSearchDoctor;
import form.patient.FormAddPatient;

import form.patient.FormSearchPatient;
import java.awt.BorderLayout;
import javax.swing.JDialog;

/**
 *
 * @author Mira
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
         setLocationRelativeTo(null);
         this.setTitle("Loged in doctor: " + Controller.getInstanca().getCurrentDoctor().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDoctor = new javax.swing.JMenu();
        menuItemAddDoctor = new javax.swing.JMenuItem();
        menuItemSearchDoctor = new javax.swing.JMenuItem();
        menuPatient = new javax.swing.JMenu();
        menuItemAddPatient = new javax.swing.JMenuItem();
        menuItemSearchPatient = new javax.swing.JMenuItem();
        menuExamination = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        menuIllness = new javax.swing.JMenu();
        menuRefer = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuMedication = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuRecipe = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuDoctor.setText("Doctor");

        menuItemAddDoctor.setText("Add new doctor");
        menuItemAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuItemAddDoctor);

        menuItemSearchDoctor.setText("Search doctors");
        menuItemSearchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchDoctorActionPerformed(evt);
            }
        });
        menuDoctor.add(menuItemSearchDoctor);

        jMenuBar1.add(menuDoctor);

        menuPatient.setText("Patient");

        menuItemAddPatient.setText(" Add new patient");
        menuItemAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuItemAddPatient);

        menuItemSearchPatient.setText(" Search patients");
        menuItemSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchPatientActionPerformed(evt);
            }
        });
        menuPatient.add(menuItemSearchPatient);

        jMenuBar1.add(menuPatient);

        menuExamination.setText("Examination");

        jMenuItem8.setText("Add new examination");
        menuExamination.add(jMenuItem8);

        jMenuItem9.setText("Search examination");
        menuExamination.add(jMenuItem9);

        jMenuBar1.add(menuExamination);

        menuIllness.setText("Illness");
        jMenuBar1.add(menuIllness);

        menuRefer.setText("Refer");

        jMenuItem10.setText("Search refer");
        menuRefer.add(jMenuItem10);

        jMenuBar1.add(menuRefer);

        menuMedication.setText("Medication");

        jMenuItem5.setText("Add new medication");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuMedication.add(jMenuItem5);

        jMenuItem6.setText("Search medications");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuMedication.add(jMenuItem6);

        jMenuItem11.setText("Delete medication");
        menuMedication.add(jMenuItem11);

        jMenuBar1.add(menuMedication);

        menuRecipe.setText("Recipe");
        jMenuBar1.add(menuRecipe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchPatientActionPerformed
        FormSearchPatient f = new FormSearchPatient();
        JDialog d = new JDialog(this, "Searching for patient", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_menuItemSearchPatientActionPerformed

    private void menuItemAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddPatientActionPerformed
        FormAddPatient f = new FormAddPatient();
        JDialog d = new JDialog(this, "Adding new patient", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_menuItemAddPatientActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuItemAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddDoctorActionPerformed
        FormAddDoctor f = new FormAddDoctor();
        JDialog d = new JDialog(this, "Adding new doctor", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_menuItemAddDoctorActionPerformed

    private void menuItemSearchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchDoctorActionPerformed
        FormSearchDoctor f = new FormSearchDoctor();
        JDialog d = new JDialog(this, "Searching for doctor", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_menuItemSearchDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuDoctor;
    private javax.swing.JMenu menuExamination;
    private javax.swing.JMenu menuIllness;
    private javax.swing.JMenuItem menuItemAddDoctor;
    private javax.swing.JMenuItem menuItemAddPatient;
    private javax.swing.JMenuItem menuItemSearchDoctor;
    private javax.swing.JMenuItem menuItemSearchPatient;
    private javax.swing.JMenu menuMedication;
    private javax.swing.JMenu menuPatient;
    private javax.swing.JMenu menuRecipe;
    private javax.swing.JMenu menuRefer;
    // End of variables declaration//GEN-END:variables

   
}
